### ISSUE TITLE
Backup of members

### ISSUE THREAD

**Issue by Karina5005** [cloud-labs-infra/github-backup#5]
Backup information about members of organization with theirs roles.
Should be save in dir `people` in `{login}.json` file with format:
```
{
    "login": "example",
    "url": "https://api.github.com/users/example",
    "html_url": "https://github.com/example",
    "role": "member",
    "state": "active",
}
```

**Comment by bissquit** [comment]
Keep in mind please that members restoring will produce email traffic to these members. Possible we should add argument like `--restore-members` (or any naming you want) to disable this action by default (`store_true` [option in argparse lib](https://docs.python.org/3/library/argparse.html#action))
